### ISSUE TITLE
Section on hacking the scenegraph

### ISSUE THREAD

**Issue by luzpaz** [qingfengxia/FreeCAD_Mod_Dev_Guide#15]
Documentation:
* https://www.freecadweb.org/wiki/Scenegraph

Examples:  
* [Camera motion in Linux absent](https://www.forum.freecadweb.org/viewtopic.php?p=328328#p328477)
* [Question: is there a way to magnify a point or node when the crosshair is in it's vicinity](https://www.forum.freecadweb.org/viewtopic.php?f=3&t=39161&start=30#p333732)
* [Civil engineering feature implementation (Transportation Engineering)](https://www.forum.freecadweb.org/viewtopic.php?f=8&t=22277&p=332557#p332557)

**Comment by qingfengxia** [comment]
link added in chap 1
