### ISSUE TITLE
How to setup different development environments

### ISSUE THREAD

**Issue by luzpaz** [qingfengxia/FreeCAD_Mod_Dev_Guide#16]
Something about how to setup the following environments for FC development: 
* QtCreator for Linux/OSX/Windows  
* KDevelop
* Atom
* PyCharm  
* Eclipse  
* Vim/NeoVIM  
* Docker  
Etc...

**Comment by qingfengxia** [comment]
that is too much time-consuming, also deviating from the key note of this book .

Since FreeCAD use cmake, so setup or build is not locked to any IDE.

**Comment by luzpaz** [comment]
fair enough, i'll spin this off in to another project then

**Comment by qingfengxia** [comment]
The major concern is I do not have the time and exprience to do that, and I use scite as my IDE.


Qingfeng Xia
Senior Research Software Engineer, Culham Centre of Fusion Energy, UKAEA

https://github.com/qingfengxia
https://www.researchgate.net/profile/Qingfeng_Xia
personal website: https://www.iesensor.com


________________________________

**Comment by luzpaz** [comment]
I get it. No worries.
