### ISSUE TITLE
Python Debugging with python debugger (pdb) and pdbpp

### ISSUE THREAD

**Issue by luzpaz** [qingfengxia/FreeCAD_Mod_Dev_Guide#17]
https://forum.freecadweb.org/viewtopic.php?f=10&t=35383  
https://www.youtube.com/watch?v=P0pIW5tJrRM

**Comment by qingfengxia** [comment]
I am more interested on debugging c++ code, I just wonder how it is possible

**Comment by qingfengxia** [comment]
https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2019
I found visual studio can do mixing debug, not sure other IDE can do this?  It seems possible, I will try out later on VScode

**Comment by qingfengxia** [comment]
Thank you, I have read that, and include that whole tutorial as an appendix of my book for easy access.  While I will work on c++ and python dual debug.
