### ISSUE TITLE
Type system clarification

### ISSUE THREAD

**Issue by Vanuan** [qingfengxia/FreeCAD_Mod_Dev_Guide#22]
Regarding this chapter: https://github.com/qingfengxia/FreeCAD_Mod_Dev_Guide/blob/master/chapters/3.FreeCAD_Base_App_modules.md#type-baseclass-pyobjectbase

Instead of listing the code, it would be more useful to document the purpose of the type system and how it's being used.

See my investigation here:
https://github.com/FreeCAD/FreeCAD/pull/3802#discussion_r471245659

I think the main reason for this is serialization and code inspection. So that document object instances can be created from strings stored in a FCStd file, and object instances be inspected in a Python console. And more importantly, to decouple C++ implementation from the UI appearance (Property and type names in a view toolbar).

I don't think it has anything to do with reference counting, outside the PyObject exports, does it?

A more practical use case is the `TypeId` and `addObject` implementation. Using `addObject` from Python you can create instances of C++ classes and map them to the Python type system.

As most of workbenches are developed in Python nowadays, there should be some recommendation on how to identify object types. E.g.:

> You may use `TypeId` if you want to use document object properties
> You must use `isinstance` to determine that the object has a particular method, as TypeId can be re-implemented by a different class

**Comment by qingfengxia** [comment]
thank your for pointing out this bug.  I need  some time to tidy up also incorproate your finding here. 

Type.h and BaseClass.h has been split out to work .             
https://github.com/qingfengxia/cppBase
