### ISSUE TITLE
More elaborate information on ccache

### ISSUE THREAD

**Issue by luzpaz** [qingfengxia/FreeCAD_Mod_Dev_Guide#5]
https://github.com/qingfengxia/FreeCAD_Mod_Dev_Guide/blob/master/chapters/9.FreeCAD%20Module%20testing%20and%20debugging.md

* @bblacey shares"[Developers - if you want must FASTER local builds, install GNU ccache](https://forum.freecadweb.org/viewtopic.php?f=10&t=16481)" thread
* https://www.virag.si/2015/07/use-ccache-with-cmake-for-faster-compilation/

**Comment by qingfengxia** [comment]
add more inforation in ch10
